# My Data Science Notebook

## Introduction  
This notebook contains information about data science tools, languages, libraries, and examples of simple arithmetic expressions.

## Data Science Languages  
- Python  
- R  
- SQL  
- Julia  
- Scala  

## Data Science Libraries  
- Pandas  
- NumPy  
- Matplotlib  
- Scikit-learn  
- TensorFlow  

## Data Science Tools  
| Tool          | Description                     |  
|---------------|---------------------------------|  
| Jupyter       | Notebook environment            |  
| RStudio       | IDE for R programming           |  
| Apache Spark  | Big data processing framework   |  

## Arithmetic Expressions  
Below are examples of arithmetic expressions in Python.

### Example 1: Multiplication and Addition  
```python
# Multiplication and addition example  
result = (5 * 4) + 3  
result